workflows:
  ios-only-build:
    name: iOS Only Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Подготовка iOS (генерация недостающих файлов)
        script: flutter create .

      - name: Установка CocoaPods
        script: |
          cd ios
          pod install

      - name: Сборка iOS-приложения без подписи
        script: flutter build ios --release --no-codesign

      - name: Архивация Runner.app
        script: |
          mkdir -p build/runner
          cp -R build/ios/iphoneos/Runner.app build/runner/
          cd build/runner
          zip -r runner.apa.zip Runner.app

    artifacts:
      - build/runner/runner.apa.zip

    publishing:
      email:
        recipients:
          - 231549@astanait.edu.kz
        notify:
          success: true
          failure: true
