workflows:
  ios-build-fix:
    name: iOS Build without -G
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Generate Podfile (if missing)
        script: |
          if [ ! -f "ios/Podfile" ]; then
            flutter build ios --release --no-codesign || true
          fi
      - name: Run pod install
        script: |
          cd ios
          pod install
          cd ..
      - name: Remove '-G' from project files
        script: |
          find ios -type f \( -name "*.xcconfig" -o -name "project.pbxproj" \) -exec sed -i '' 's/-G//g' {} +
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app

