workflows:
  ios-build-fix:
    name: iOS Build with -G Fix
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Create iOS project if missing
        script: |
          if [ ! -f "ios/Podfile" ]; then
            flutter build ios --release --no-codesign || true
          fi
      - name: Run pod install
        script: |
          cd ios
          pod install
          cd ..
      - name: Remove unsupported '-G' flag
        script: |
          find ios/Pods -type f -name '*.xcconfig' -exec sed -i '' 's/-G//g' {} +
      - name: Build iOS app (no codesign)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
