platform :ios, '11.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete('GCC_WARN_INHIBIT_ALL_WARNINGS')
        config.build_settings['OTHER_CFLAGS'] = config.build_settings['OTHER_CFLAGS'].to_s.gsub('-G', '')
      end

      # Пример: фикс для BoringSSL-GRPC
      if target.name == 'BoringSSL-GRPC'
        puts "Cleaning up flags for #{target.name}"
        target.build_configurations.each do |config|
          flags = config.build_settings['OTHER_CFLAGS']
          if flags.is_a? String
            config.build_settings['OTHER_CFLAGS'] = flags.gsub('-G', '')
          end
        end
      end
    end
  end
end
